import {env} from 'cloudflare:workers';
import {db,identity,owner,staff,origin,body,fail,HttpError,rateLimit} from '@/lib/server';
import {profileInput,entryInput} from '@/lib/validation';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{const u=await identity(r),d=db();const profile=await d.prepare('SELECT * FROM profiles WHERE id=?').bind(u.userId).first<any>();const rows=await d.prepare(`SELECT e.*,p.name,p.username,p.avatar FROM entries e JOIN profiles p ON p.id=e.owner WHERE ((e.kind IN ('post','video','event','comment','squad','live') AND e.status='published' AND e.publish_at<=?) OR (e.owner=? AND e.kind IN ('saved','rsvp','vote','like','block','feedback','activity')) OR (?=1 AND e.kind IN ('post','video','event','report','feedback','live'))) AND (e.kind!='comment' OR EXISTS (SELECT 1 FROM entries parent WHERE parent.id=e.target AND parent.status='published' AND parent.publish_at<=?)) AND (e.owner=? OR NOT EXISTS (SELECT 1 FROM entries b WHERE b.kind='block' AND b.owner=? AND b.target=e.owner)) ORDER BY e.created_at DESC LIMIT 500`).bind(Date.now(),u.userId,staff(u.userId)?1:0,Date.now(),u.userId,u.userId).all<any>();const members=await d.prepare("SELECT id,username,name,bio,region,avatar FROM profiles WHERE NOT EXISTS (SELECT 1 FROM entries b WHERE b.owner=? AND b.kind='block' AND b.target=profiles.id) LIMIT 300").bind(u.userId).all();return Response.json({userId:u.userId,profile:profile?{...profile,preferences:JSON.parse(profile.preferences)}:null,entries:rows.results.map(r=>({...r,data:JSON.parse(r.data)})),members:members.results,isOwner:owner(u.userId),isStaff:staff(u.userId),syncAvailable:!!(env.YOUTUBE_API_KEY&&env.YOUTUBE_CHANNEL_ID)},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(r:Request){try{origin(r);const u=await identity(r),d=db(),input=await body(r);
if(input.action==='profile'){const p=profileInput.parse(input.profile);await d.prepare(`INSERT INTO profiles(id,username,name,bio,region,preferences,accepted_at,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,name=excluded.name,bio=excluded.bio,region=excluded.region,preferences=excluded.preferences`).bind(u.userId,p.username,p.name,p.bio,p.region,JSON.stringify(p.preferences),Date.now(),Date.now()).run();return Response.json({ok:true})}
if(!await d.prepare('SELECT id FROM profiles WHERE id=?').bind(u.userId).first())throw new HttpError(409,'Create your community profile first.');await rateLimit(u.userId);
if(input.action==='approve'){if(!owner(u.userId))throw new HttpError(403,'Creator access required.');await d.prepare("UPDATE entries SET status='published' WHERE id=? AND kind='video'").bind(String(input.id)).run();return Response.json({ok:true})}
if(input.action==='moderate'){if(!staff(u.userId))throw new HttpError(403,'Moderator access required.');if(!['remove','dismiss'].includes(input.resolution))throw new HttpError(400,'Invalid resolution.');const report=await d.prepare("SELECT * FROM entries WHERE id=? AND kind='report'").bind(String(input.id)).first<any>();if(!report)throw new HttpError(404,'Report not found.');const statements=[d.prepare("UPDATE entries SET status='resolved' WHERE id=?").bind(report.id)];if(input.resolution==='remove')statements.push(d.prepare("UPDATE entries SET status='hidden' WHERE id=? AND kind IN ('post','video','event','comment','squad')").bind(report.target));await d.batch(statements);return Response.json({ok:true})}
if(input.action!=='create')throw new HttpError(400,'Unknown action.');const v=entryInput.parse(input.entry);if(['post','video','event','live'].includes(v.kind)&&!owner(u.userId))throw new HttpError(403,'Creator access required.');if(['post','comment','report','feedback'].includes(v.kind)&&!v.data.body)throw new HttpError(400,'Please add some text.');if(['video','event','live'].includes(v.kind)&&!v.data.title)throw new HttpError(400,'Please add a title.');
if(['comment','rsvp','vote','like','report'].includes(v.kind)){const target=await d.prepare("SELECT * FROM entries WHERE id=? AND status='published' AND publish_at<=?").bind(v.target,Date.now()).first<any>();if(!target||!['post','video','event','comment','squad','live'].includes(target.kind))throw new HttpError(404,'This item is unavailable.');if(['rsvp','vote'].includes(v.kind)&&target.kind!=='event')throw new HttpError(400,'Choose a community event.');if(v.kind==='vote'&&!(JSON.parse(target.data).choices||[]).includes(v.data.title))throw new HttpError(400,'Choose one of the poll options.')}
if(v.kind==='block'){if(v.target===u.userId)throw new HttpError(400,'You cannot block yourself.');if(!await d.prepare('SELECT id FROM profiles WHERE id=?').bind(v.target).first())throw new HttpError(404,'Member not found.')}
const unique=['saved','rsvp','vote','like','block','squad','live','activity'].includes(v.kind);const key=unique?`${u.userId}:${v.kind}:${['squad','live'].includes(v.kind)?'single':v.target}`:crypto.randomUUID();await d.prepare(`INSERT INTO entries(id,kind,owner,target,data,created_at,publish_at,status) VALUES(?,?,?,?,?,?,?,'published') ON CONFLICT(id) DO UPDATE SET data=excluded.data,publish_at=excluded.publish_at,status='published'`).bind(key,v.kind,u.userId,v.target,JSON.stringify(v.data),Date.now(),v.publishAt).run();return Response.json({ok:true,id:key})}catch(e){return fail(e)}}
export async function DELETE(r:Request){try{origin(r);const u=await identity(r),d=db(),input=await body(r);if(input.action==='account'){if(input.confirm!=='DELETE')throw new HttpError(400,'Type DELETE to confirm.');const p=await d.prepare('SELECT avatar FROM profiles WHERE id=?').bind(u.userId).first<any>();if(p?.avatar&&env.BUCKET)await env.BUCKET.delete(p.avatar);await d.batch([d.prepare('DELETE FROM entries WHERE target IN (SELECT id FROM entries WHERE owner=?)').bind(u.userId),d.prepare('DELETE FROM entries WHERE owner=? OR target=?').bind(u.userId,u.userId),d.prepare('DELETE FROM profiles WHERE id=?').bind(u.userId)]);return Response.json({ok:true})}const row=await d.prepare('SELECT owner,kind FROM entries WHERE id=?').bind(String(input.id)).first<any>();if(!row)throw new HttpError(404,'Item not found.');if(row.owner!==u.userId&&!(staff(u.userId)&&['post','video','event','comment','squad','report'].includes(row.kind)))throw new HttpError(403,'You cannot remove this item.');await d.batch([d.prepare('DELETE FROM entries WHERE target=?').bind(String(input.id)),d.prepare('DELETE FROM entries WHERE id=?').bind(String(input.id))]);return Response.json({ok:true})}catch(e){return fail(e)}}
